person:
  name: ${random.value}
  age: ${random.int}
  address: hebei@qq.com
  birth-day: 1998/02/12
  family:
    father: ${random.uuid}
    mom: what
  love:
    - eat
    - ${person.what:默认值}
    - ${person.family.mom}
test: 测试属性
spring:
  profiles:
    active: prod
logging:
  file:
    name: F:\logs\mylog.log
  level:
    root: warn
    cn:
      guzx: trace
    org.springframework: warn
#debug: true
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 85
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 86
---
spring:
  config:
    activate:
      on-profile: test

#person.name=guzx
#person.age=23
#person.address=hunan
#person.birthday=1997/07/12
#person.family.father=guwg
#person.family.mom=zhoucf
logging:
  level:
    cn:
      guzx: trace
#person.love=read,song